<?php

namespace Database\Seeders;

use App\Models\Sample;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SampleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV1',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-27'),
            'collectorname' => 'Vern',
            'commonname' => 'Tilapia',
            'collectmethod' => 'Gill nets',
            'site_id' => 1,
            'time' => Carbon::createFromTimeString('09:45:00'),
            'latitude' => 5.409002,
            'longitude' => 103.088226,
            'depth' => null,
            'weight' => 86.5,
            'standardL' => 12.0,
            'totalL' => 15.0,
            'forkL' => 14.7,
            'species_id' => 1,
            'status' => 'accepted',
            'photo' => 'images/DyKawYiGocTob1wn1RbrvGFPeytyDdCDRpH28gJF.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV2',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-27'),
            'collectorname' => 'Vern',
            'commonname' => 'Seriding',
            'collectmethod' => 'Gill nets',
            'site_id' => 1,
            'time' => Carbon::createFromTimeString('16:40:00'),
            'latitude' => 5.409002,
            'longitude' => 103.088226,
            'depth' => null,
            'weight' => 2.7,
            'standardL' => 4.7,
            'totalL' => 6.0,
            'forkL' => 5.1,
            'species_id' => 2,
            'status' => 'accepted',
            'photo' => 'images/IjGmu12goQidFbJHrkMHg1iko16hlWCQ9abClKrj.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV3',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Belanak',
            'collectmethod' => 'Gill nets',
            'site_id' => 1,
            'time' => Carbon::createFromTimeString('08:00:00'),
            'latitude' => 5.409002,
            'longitude' => 103.088226,
            'depth' => null,
            'weight' => 38.1,
            'standardL' => 12.7,
            'totalL' => 15.6,
            'forkL' => 14.3,
            'species_id' => 3,
            'status' => 'accepted',
            'photo' => 'images/74XoWvHToRBhugxZ3VCjsEGnze2ylVQmjPXzQdQE.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV4',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Seriding',
            'collectmethod' => 'Gill nets',
            'site_id' => 1,
            'time' => Carbon::createFromTimeString('15:20:00'),
            'latitude' => 5.409002,
            'longitude' => 103.088226,
            'depth' => null,
            'weight' => 2.3,
            'standardL' => 4.2,
            'totalL' => 5.5,
            'forkL' => 5.0,
            'species_id' => 4,
            'status' => 'accepted',
            'photo' => 'images/FeeR6PETIOjS9OF4Jw7IOleJ0HQGcvBlsJrEessg.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV5',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-27'),
            'collectorname' => 'Vern',
            'commonname' => 'Ubi Belontok',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('16:30:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 9.9,
            'standardL' => 7.7,
            'totalL' => 9.4,
            'forkL' => null,
            'species_id' => 5,
            'status' => 'accepted',
            'photo' => 'images/J2np6tmnsmIVBOYBFMcolp6uKXOPOdIbrB3EGuCq.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV6',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-27'),
            'collectorname' => 'Vern',
            'commonname' => 'Seriding',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('16:50:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 19.3,
            'standardL' => 8.3,
            'totalL' => 11.2,
            'forkL' => 9.5,
            'species_id' => 6,
            'status' => 'accepted',
            'photo' => 'images/phUVGSRvgiWZMQ2620624FUHPgDkYuFtI5MGVy7h.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV7',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Marble butis',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('09:54:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 190.1,
            'standardL' => 20.9,
            'totalL' => 24.7,
            'forkL' => null,
            'species_id' => 7,
            'status' => 'accepted',
            'photo' => 'images/x6ntj8H3Izk53BjPlI0Y6V3L6Gb59fZWhsv9rUQG.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV8',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Buntal',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('09:54:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 73.4,
            'standardL' => 10.1,
            'totalL' => 12.4,
            'forkL' => null,
            'species_id' => 8,
            'status' => 'accepted',
            'photo' => 'images/lCmLk1Q0K7h9iFnn7OGUflH9UEyvJotVBvVnMTd0.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV9',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Sebekah',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('09:54:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 37.4,
            'standardL' => 10.2,
            'totalL' => 12.6,
            'forkL' => null,
            'species_id' => 9,
            'status' => 'accepted',
            'photo' => 'images/tKXE4CLnxIlqOOFSqlvd0rR5V1u50v1xJbmNiAlH.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV10',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Seriding',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('09:54:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 29.0,
            'standardL' => 9.0,
            'totalL' => 11.5,
            'forkL' => 10.0,
            'species_id' => 10,
            'status' => 'accepted',
            'photo' => 'images/pZ6LCY6vTGCI3WZdVnVhsqekp5ivPLUIANW9oVhG.jpg',
            'type' => 'freshwater',
        ]);

        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV11',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Seriding',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('09:54:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 5.8,
            'standardL' => 5.7,
            'totalL' => 7.6,
            'forkL' => 6.6,
            'species_id' => 4,
            'status' => 'accepted',
            'photo' => 'images/OwOVjVYTjHSXs1d07alFEWBlukfZ9UlwpAKdSOe5.jpg',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV12',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Belanak',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('09:54:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 75.7,
            'standardL' => 15.7,
            'totalL' => 19,
            'forkL' => 17.6,
            'species_id' => 3,
            'status' => 'accepted',
            'photo' => '',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV13',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Gobi',
            'collectmethod' => 'Gill nets',
            'site_id' => 2,
            'time' => Carbon::createFromTimeString('09:54:00'),
            'latitude' => 5.410437,
            'longitude' => 103.090649,
            'depth' => null,
            'weight' => 50.6,
            'standardL' => 16.2,
            'totalL' => 19.5,
            'forkL' => null,
            'species_id' => 11,
            'status' => 'accepted',
            'photo' => 'images/dtDhMK3rhIoMpUOhqEEAhq0xwvvVJ1Dpaed5h4Gv.jpg',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV14',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-27'),
            'collectorname' => 'Vern',
            'commonname' => 'Sumpit',
            'collectmethod' => 'Gill nets',
            'site_id' => 3,
            'time' => Carbon::createFromTimeString('09:00:00'),
            'latitude' => 5.414536,
            'longitude' => 103.08488,
            'depth' => null,
            'weight' => 24.6,
            'standardL' => 9.5,
            'totalL' => 11.5,
            'forkL' => 11,
            'species_id' => 12,
            'status' => 'accepted',
            'photo' => 'images/VDeaLusCrHHy2XbJgoeSogcrLGPrUea7y83k6qwo.jpg',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV15',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Seriding',
            'collectmethod' => 'Gill nets',
            'site_id' => 3,
            'time' => Carbon::createFromTimeString('15:20:00'),
            'latitude' => 5.414536,
            'longitude' => 103.08488,
            'depth' => null,
            'weight' => 20.1,
            'standardL' => 8.2,
            'totalL' => 10.5,
            'forkL' => 9.4,
            'species_id' => 2,
            'status' => 'accepted',
            'photo' => null,
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV16',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Ubi Belontok',
            'collectmethod' => 'Gill nets',
            'site_id' => 4,
            'time' => Carbon::createFromTimeString('12:00:00'),
            'latitude' => 5.407801,
            'longitude' => 103.090683,
            'depth' => null,
            'weight' => 28.1,
            'standardL' => 11.7,
            'totalL' => 14.5,
            'forkL' => null,
            'species_id' => 5,
            'status' => 'accepted',
            'photo' => 'images/jCl6F9qVgLoaiWVd2Tov1J6bvOw1M2FecK8b2B0V.jpg',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'UMTF 11007',
            'samplingid' => 'UMTV17',
            'identifiedBy' => 'Siti Tafzil / Mizuki',
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2022-10-28'),
            'collectorname' => 'Vern',
            'commonname' => 'Bulan',
            'collectmethod' => 'Gill nets',
            'site_id' => 4,
            'time' => Carbon::createFromTimeString('12:00:00'),
            'latitude' => 5.407801,
            'longitude' => 103.090683,
            'depth' => null,
            'weight' => 257.3,
            'standardL' => 24.6,
            'totalL' => 30.5,
            'forkL' => 25.5,
            'species_id' => 13,
            'status' => 'accepted',
            'photo' => 'images/39at8KTkZ9MBmhmZqN3Zo7jN8IAXbK87nbTfVkLi.jpg',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'MM6',
            'samplingid' => 'MM6',
            'identifiedBy' => null,
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2021-10-16'),
            'collectorname' => 'Dr Saiful, Jimi, Dr Maizah',
            'commonname' => 'Spotted catfish',
            'collectmethod' => 'Gill nets',
            'site_id' => 5,
            'time' => Carbon::createFromTimeString('14:30:00'),
            'latitude' => 4.789321991,
            'longitude' => 100.627503,
            'depth' => 1.7,
            'weight' => 839.5,
            'standardL' => 34.5,
            'totalL' => 43.5,
            'forkL' => 37,
            'species_id' => 14,
            'status' => 'accepted',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'MM7',
            'samplingid' => 'MM7',
            'identifiedBy' => null,
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2021-10-16'),
            'collectorname' => 'Dr Saiful, Jimi, Dr Maizah',
            'commonname' => 'Spotted catfish',
            'collectmethod' => 'Gill nets',
            'site_id' => 5,
            'time' => Carbon::createFromTimeString('14:30:00'),
            'latitude' => 4.789321991,
            'longitude' => 100.627503,
            'depth' => 1.7,
            'weight' => 839.5,
            'standardL' => 34.5,
            'totalL' => 43.5,
            'forkL' => 37,
            'species_id' => 14,
            'status' => 'accepted',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'MM8',
            'samplingid' => 'MM8',
            'identifiedBy' => null,
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2021-10-16'),
            'collectorname' => 'Dr Saiful, Jimi, Dr Maizah',
            'commonname' => 'Spotted catfish',
            'collectmethod' => 'Gill nets',
            'site_id' => 5,
            'time' => Carbon::createFromTimeString('14:30:00'),
            'latitude' => 4.789321991,
            'longitude' => 100.627503,
            'depth' => 1.7,
            'weight' => 839.5,
            'standardL' => 34.5,
            'totalL' => 43.5,
            'forkL' => 37,
            'species_id' => 14,
            'status' => 'accepted',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'MM9',
            'samplingid' => 'MM9',
            'identifiedBy' => null,
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2021-10-16'),
            'collectorname' => 'Dr Saiful, Jimi, Dr Maizah',
            'commonname' => 'Spotted catfish',
            'collectmethod' => 'Gill nets',
            'site_id' => 5,
            'time' => Carbon::createFromTimeString('14:30:00'),
            'latitude' => 4.789321991,
            'longitude' => 100.627503,
            'depth' => 1.7,
            'weight' => 839.5,
            'standardL' => 34.5,
            'totalL' => 43.5,
            'forkL' => 37,
            'species_id' => 14,
            'status' => 'accepted',
            'type' => 'freshwater',
        ]);
        Sample::create([
            'refno' => 'MM10',
            'samplingid' => 'MM10',
            'identifiedBy' => null,
            'identifiedDate' => null,
            'datecollected' => Carbon::create('2021-10-16'),
            'collectorname' => 'Dr Saiful, Jimi, Dr Maizah',
            'commonname' => 'Spotted catfish',
            'collectmethod' => 'Gill nets',
            'site_id' => 5,
            'time' => Carbon::createFromTimeString('14:30:00'),
            'latitude' => 4.789321991,
            'longitude' => 100.627503,
            'depth' => 1.7,
            'weight' => 839.5,
            'standardL' => 34.5,
            'totalL' => 43.5,
            'forkL' => 37,
            'species_id' => 14,
            'status' => 'accepted',
            'type' => 'freshwater',
        ]);
    }
}
